author: "Kuba Suder"
title: "sdk.blue"
description: "A curated list of libraries & SDKs for the Bluesky API and AT Protocol"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

destination: "./public"

defaults:
  - scope:
      path: ""
    values:
      layout: default

exclude:
  - "[A-Z]*"
  - config
